### ISSUE TITLE
Should not send ERR packet after receiving ERR packet from server.

### ISSUE THREAD

**Issue by tazahmd** [msoulier/tftpy#106]
In `TftpStates.TftpStateSentRRQ `and `TftpStates.TftpStateSentWRQ` class when an ERR packet is received form server it should not send ERR packet to server again because server would have closed its session and [RFC](https://tools.ietf.org/html/rfc1350) does not mention about it.

>         elif isinstance(pkt, TftpPacketERR):
>             self.sendError(TftpErrors.IllegalTftpOp)
>             log.debug("Received ERR packet: %s", pkt)
>             if pkt.errorcode == TftpErrors.FileNotFound:
>                 raise TftpFileNotFoundError("File not found")
>             else:
>                 raise TftpException("Received ERR from server: {}".format(pkt))

**Comment by msoulier** [comment]
Valid point.

**Comment by msoulier** [comment]
Fixed in 7c62b3472627f4bfe85e359d80d2b9eff2588ce7
