### ISSUE TITLE
Space based folder names are not handled

### ISSUE THREAD

**Issue by Sududboss** [msoulier/tftpy#123]
if the source folder has a names with spaces it is not able to reach that folder and causing problem 

simple hack is use the "" for specifying the path folder

**Comment by msoulier** [comment]
Directory names with spaces in them are evil and should be purged from the Earth. 

That said, are you referring to passing them into the sample server, or just having any directory with spaces in it?

**Comment by msoulier** [comment]
I added an upload test with spaces in it and it worked. If you don't have an example of a failure then I'll have to close this.

**Comment by msoulier** [comment]
Need a reproduction scenario. I have updated the unit tests.

**Comment by Sududboss** [comment]
hi .., sorry i missed your conversation :(

C:\Users\irgvuop\OneDrive - Test Technologies\Desktop-1\Extracted files\monitor_mem\
