### ISSUE TITLE
Error to end tftp server

### ISSUE THREAD

**Issue by vjuagar** [msoulier/tftpy#132]
Hi, i have a problem to end the sesion on the server.

My code is:

`import tftpy`
`import time`
`server = tftpy.TftpServer('C:/backup')`
`server.listen('0.0.0.0', 69)`
`time.sleep(5)`
`server.stop(True)`

the server start correctly, but i can't stop

**Comment by msoulier** [comment]
Considering that your code will block on server.listen(), why do you 
expect the rest of the code to be run at all?

The stop() method is meant to be called by another thread. Or just break 
out of listen() via a signal and it will be stopped.

Mike
