### ISSUE TITLE
Single port mode

### ISSUE THREAD

**Issue by slintak** [msoulier/tftpy#49]
Is there easy way how to implement single port mode in tftpy -- server listens and responds on the same port (i.e. 69)?

Right now, I'm using [opentftp](http://sourceforge.net/projects/tftp-server/) for serving firmwares into devices with 8bit MCU. Because of NATs and firewalls, I have to use single port. I would like to use Python implementation of TFTP, because the rest of my project is written in Python.

After reading the code, I'm not sure if this single port can be easily done. What part should change?

**Comment by msoulier** [comment]
Merging with issue #44
