### ISSUE TITLE
Any plan to support python3?

### ISSUE THREAD

**Issue by triobox** [msoulier/tftpy#54]
Any plan to support python3?

**Comment by msoulier** [comment]
Yeah, I need to do some work to make it support 2 and 3 at the same time. It shouldn't be too hard.

**Comment by gabor-zinemath** [comment]
How is the porting to python 3 going?

**Comment by em92** [comment]
Quite good python 3 port: https://github.com/ZuljinSBK/tftpy

**Comment by gabor-zinemath** [comment]
Thank you but I already ported the necessary parts to python3. Some exception handling and 'key in dict' was in need of an update and it works now!

**Comment by msoulier** [comment]
I'm looking at this now.

**Comment by msoulier** [comment]
I have just merged the initial work but the tests are failing. Still work to do.

**Comment by msoulier** [comment]
Run "make test PY=python3" if you want to see the explosions. :)

**Comment by msoulier** [comment]
Fixed in 0.8.0.
