### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by sanseihappa** [msoulier/tftpy#71]
Would you be able to release a package that has IPv6 addressing support?

**Comment by msoulier** [comment]
It would take me a while. There is a pull request that might have that
support if you want to look at it.

Mike

**Comment by sanseihappa** [comment]
I'm not seeing a PR nor does it look like any branches have changes.  I'll work on a PR...

**Comment by sethalicious** [comment]
In the listen method in TftpServer, https://github.com/msoulier/tftpy/blob/master/tftpy/TftpServer.py#L91

Changing AF_INET to AF_INET6 would support both ipv6 and ipv4 address families.

**Comment by sanseihappa** [comment]
https://github.com/msoulier/tftpy/pull/74

**Comment by kwmlodozeniec** [comment]
Would love to see IPv6 support for the client.

**Comment by msoulier** [comment]
On 09/11/17 Krzysztof Mlodozeniec said:

> Would love to see IPv6 support for the client.

Understood. I don't have my HE tunnel anymore but I should be able to
manage it with a site-local fe80 address.

Mike

**Comment by msoulier** [comment]
I will leave this open as a feature request for full ipv6 support.

**Comment by msoulier** [comment]
Merging this with #18.
