### ISSUE TITLE
TftpShared.py should not be invoking logging.basicConfig()

### ISSUE THREAD

**Issue by sanseihappa** [msoulier/tftpy#86]
`logging.basicConfig()` should be reserved for usage in the main application.  The current usage in `tftpy` package results in potentially ignoring subsequent calls the `logging.basicConfig()` inside the main application using `tftpy`:

> This function does nothing if the root logger already has handlers configured for it.

(https://docs.python.org/3/library/logging.html#logging.basicConfig)

**Comment by wlq6037** [comment]
just see "Note :This function should be called from the main thread before other threads are started. In versions of Python prior to 2.7.1 and 3.2, if this function is called from multiple threads, it is possible (in rare circumstances) that a handler will be added to the root logger more than once, leading to unexpected results such as messages being duplicated in the log" .

At 2018-04-30 22:46:16, "sanseihappa" <notifications@github.com> wrote:


logging.basicConfig() should be reserved for usage in the main application. The current usage in tftpy package results in potentially ignoring subsequent calls the logging.basicConfig() inside the main application using tftpy:

This function does nothing if the root logger already has handlers configured for it.

(https://docs.python.org/3/library/logging.html#logging.basicConfig)
