### ISSUE TITLE
Problem using tftpy with python 3.4.6

### ISSUE THREAD

**Issue by AndreasDa** [msoulier/tftpy#92]
I tried to make a simple server and client using the tftpy module. However, I always get a TypeError:
unsupported operand type(s) for %: 'bytes' and 'int'
when I run the client.
Bellow is the full output: 
Traceback (most recent call last):
  File "tftpClientTest.py", line 5, in <module>
    client.download("remote_filename","testtest")
  File "/usr/lib/python3.4/site-packages/tftpy/TftpClient.py", line 56, in download
    self.context.start()
  File "/usr/lib/python3.4/site-packages/tftpy/TftpContexts.py", line 391, in start
    self.sock.sendto(pkt.encode().buffer, (self.host, self.port))
  File "/usr/lib/python3.4/site-packages/tftpy/TftpPacketTypes.py", line 137, in encode
    fmt += b"%dsx" % (len(self.filename))
TypeError: unsupported operand type(s) for %: 'bytes' and 'int'

I get this error every time I try to download a file with the client. 
This error also occurs in the simple example programs provided in the documentation. 
As I'm new to python programming, I'm unsure as to where the error comes from. Maybe an issue with python 3?

**Comment by msoulier** [comment]
Python 3 is not yet supported. It is coming.

mps

**Comment by msoulier** [comment]
I see from #100 that this is still happening. I have a windows VM that I could try running this on. As you said, the tests won't run. Maybe I  can fix that too.
